spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=kesmarkiDB;encrypt=true;trustServerCertificate=true;
    username: kesmarki
    password: kesmarki
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: on